services:
  db:
    image: pgvector/pgvector:pg17  # Prebuilt Postgres image with pgvector
    container_name: postgres-pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: iZ85b4QDj7WN
      POSTGRES_DB: video_analytics
    volumes:
      - ~/.postgres_volume:/var/lib/postgresql/data